# Generated by Django 3.2.5 on 2021-07-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
